name: github pages
on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * * *' # 每分钟执行一次

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  bot:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
